### ISSUE TITLE
気になるところ

### ISSUE THREAD

**Issue by tomoyukikino** [nakapon9517/sample#1]
■その①
server.go -> main.go
のほうがいいかも。
理由：main関数があるgoファイルは、基本main.goって風潮があるから

■その②
`	e.GET("/hello:userid", func(c echo.Context) error {`
じゃなくて、
`	e.GET("/user/:id", func(c echo.Context) error {`
とかのほうがいいかも

**Comment by nakapon9517** [comment]
closed
