### ISSUE TITLE
go get

### ISSUE THREAD

**Issue by tomoyukikino** [nakapon9517/sample#6]
- [ ] install newest go
Don't use below command. because this cannot install newest go version.
```brew install go```.
Newest go version. is here.
https://golang.org/doc/install
- [ ] go get github.com/nakapon9517/sample
check ```nakapon9517/sample``` repo is cloned in macbook $GOPATH/src/github...

**Comment by nakapon9517** [comment]
Complete
<img width="1034" alt="スクリーンショット 2020-07-21 22 13 28" src="https://user-images.githubusercontent.com/62886817/88059146-68fef780-cb9f-11ea-8e4c-c16fbd8f5c05.png">

**Comment by tomoyukikino** [comment]
prefect
